--Classe 1
UPDATE Compteprojet SET ref_debit= 'CB' WHERE numcompte LIKE '12%'
UPDATE Compteprojet SET ref_debit= 'CC' WHERE numcompte LIKE '13%'
UPDATE Compteprojet SET ref_debit= 'CD' WHERE numcompte LIKE '14%'
UPDATE Compteprojet SET ref_debit= 'CA' WHERE numcompte LIKE '16%'
UPDATE Compteprojet SET ref_debit= 'DA' WHERE numcompte LIKE '18%'
UPDATE Compteprojet SET ref_debit= 'DB' WHERE numcompte LIKE '19%'
--Classe 2
UPDATE Compteprojet SET ref_debit= 'AA' WHERE numcompte LIKE '21%'
UPDATE Compteprojet SET ref_debit= 'AB' WHERE numcompte LIKE '22%' OR numcompte LIKE '23%'
UPDATE Compteprojet SET ref_debit= 'AC' WHERE numcompte LIKE '235%' OR numcompte LIKE '239%'
UPDATE Compteprojet SET ref_debit= 'AD' WHERE numcompte LIKE '24%'
UPDATE Compteprojet SET ref_debit= 'AE' WHERE numcompte LIKE '245%'
UPDATE Compteprojet SET ref_debit= 'AF' WHERE numcompte LIKE '25%'
UPDATE Compteprojet SET ref_debit= 'AH' WHERE numcompte LIKE '26%' OR numcompte LIKE '27%'
UPDATE Compteprojet SET ref_debit= 'AG' WHERE numcompte LIKE '275%'
--Classe 3
UPDATE Compteprojet SET ref_debit= 'BB' WHERE numcompte LIKE '31%' OR numcompte LIKE '32%' OR numcompte LIKE '33%' OR numcompte LIKE '34%' OR numcompte LIKE '37%' OR numcompte LIKE '38%'
--Classe 4
UPDATE Compteprojet SET ref_debit= 'DG' WHERE numcompte LIKE '40%'
UPDATE Compteprojet SET ref_debit= 'BC' WHERE numcompte LIKE '409%'
UPDATE Compteprojet SET ref_debit= 'BD' WHERE numcompte LIKE '412%' OR numcompte LIKE '413%' OR numcompte LIKE '416%' OR numcompte LIKE '418%'
UPDATE Compteprojet SET ref_credit= 'DH' WHERE numcompte LIKE '419%'
UPDATE Compteprojet SET ref_debit= 'BE', ref_credit= 'DH' WHERE numcompte LIKE '42%' OR numcompte LIKE '43%' OR numcompte LIKE '44%'
UPDATE Compteprojet SET ref_credit= 'DF' WHERE numcompte LIKE '46%'
UPDATE Compteprojet SET ref_debit= 'BE', ref_credit= 'DH' WHERE numcompte LIKE '47%'
UPDATE Compteprojet SET ref_debit= 'BY' WHERE numcompte LIKE '478%'
UPDATE Compteprojet SET ref_credit= 'DY' WHERE numcompte LIKE '479%'
UPDATE Compteprojet SET ref_credit= NULL WHERE numcompte LIKE '478%'
UPDATE Compteprojet SET ref_debit= NULL WHERE numcompte LIKE '479%'
UPDATE Compteprojet SET ref_debit= 'DE' WHERE numcompte LIKE '481%'
UPDATE Compteprojet SET ref_debit= 'DE' WHERE numcompte LIKE '484%'
UPDATE Compteprojet SET ref_debit= 'BA' WHERE numcompte LIKE '485%'
UPDATE Compteprojet SET ref_debit= 'DH' WHERE numcompte LIKE '499%'
--Classe 5
UPDATE Compteprojet SET ref_debit= 'BV' WHERE numcompte LIKE '51%'
UPDATE Compteprojet SET ref_debit= 'BW' WHERE numcompte LIKE '52%' OR numcompte LIKE '53%' OR numcompte LIKE '55%'
UPDATE Compteprojet SET ref_credit= 'DW' WHERE numcompte LIKE '52%' OR numcompte LIKE '53%' OR numcompte LIKE '56%'
UPDATE Compteprojet SET ref_debit= 'BW' WHERE numcompte LIKE '57%'
UPDATE Compteprojet SET ref_credit= 'DH' WHERE numcompte LIKE '59%'

--Classe 6
UPDATE Compteprojet SET ref_debit= 'TA' WHERE numcompte LIKE '601%' OR numcompte LIKE '602%'
UPDATE Compteprojet SET ref_debit= 'TC' WHERE numcompte LIKE '603%'
UPDATE Compteprojet SET ref_debit= 'TB' WHERE numcompte LIKE '604%' OR numcompte LIKE '605%' OR numcompte LIKE '608%'
UPDATE Compteprojet SET ref_debit= 'TD' WHERE numcompte LIKE '61%'
UPDATE Compteprojet SET ref_debit= 'TG' WHERE numcompte LIKE '62%' OR numcompte LIKE '63%'
UPDATE Compteprojet SET ref_debit= 'TH' WHERE numcompte LIKE '64%'
UPDATE Compteprojet SET ref_debit= 'TI' WHERE numcompte LIKE '65%'
UPDATE Compteprojet SET ref_debit= 'TJ' WHERE numcompte LIKE '66%' OR numcompte LIKE '69%'
UPDATE Compteprojet SET ref_debit= 'TK' WHERE numcompte LIKE '67%'

--Classe 7
UPDATE Compteprojet SET ref_credit= 'RA' WHERE numcompte = '702'
UPDATE Compteprojet SET ref_credit= 'RB' WHERE numcompte LIKE '705%'
UPDATE Compteprojet SET ref_credit= NULL WHERE numcompte = '705'
UPDATE Compteprojet SET ref_credit= 'RD' WHERE numcompte = '707'
UPDATE Compteprojet SET ref_credit= 'RC' WHERE numcompte LIKE '71%'
UPDATE Compteprojet SET ref_credit= 'RD' WHERE numcompte LIKE '73%' OR numcompte LIKE '75%' OR numcompte LIKE '77%' OR numcompte LIKE '78%'
UPDATE Compteprojet SET ref_credit= 'RE' WHERE numcompte LIKE '79%'
UPDATE Compteprojet SET ref_credit= NULL WHERE numcompte = '79'
--Classe 8
UPDATE Compteprojet SET ref_debit= 'TL' WHERE numcompte LIKE '81%' OR numcompte LIKE '83%' OR numcompte LIKE '85%' OR numcompte LIKE '87%'
UPDATE Compteprojet SET ref_credit= 'TK' WHERE numcompte LIKE '82%' OR numcompte LIKE '84%' OR numcompte LIKE '86%' OR numcompte LIKE '88%'

